version: "3"
services:
  config-server:
    environment:
      CONFIG_LOGIN_PWD: $CONFIG_LOGIN_PWD
    image: itmabo/config-server
    volumes:
      - /home/log:/home/log
    ports:
      - 9701:9701
    networks:
      - tonynet-a
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  tonynet-a:
    external:
      name: tonynet