version: "3"
services:
  config-server:
    environment:
      CONFIG_LOGIN_PWD: $CONFIG_LOGIN_PWD
    image: itmabo/config-server
    volumes:
      - /home/log:/home/log
    ports:
      - 9706:9706
#    networks:
#      - tonynet-a
    deploy:
      placement:
        constraints: [node.role==worker]
#networks:
#  tonynet-a:
#    external:
#      name: tonynet